name: Release
on:
  push:
    branches:
      - 'test-ci'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Actions Releaser
        id: actions_releaser
        uses: raulanatol/github-actions-releaser@master
        env:
          GREN_GITHUB_TOKEN: ${{ secrets.GREN_GITHUB_TOKEN }}
      - name: tests
        run: |
          cat CHANGELOG.md
